# Generated by Django 3.0.8 on 2020-07-29 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthprice', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category_json', models.TextField(default='{"category": null, "subcategory": null}')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('img', models.ImageField(upload_to='UserImages')),
                ('rating', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('postings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('acc_sts', models.CharField(choices=[('+', 'Ավելացում'), ('-', 'Պակասեցում')], max_length=1)),
                ('status', models.CharField(choices=[('p', 'Մշակում'), ('s', 'Հաջող'), ('r', 'Ձախողված')], default='p', max_length=1)),
                ('success', models.BooleanField(default=False)),
                ('paymentid', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Urgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('owner_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Post')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('owner_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Post')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Transaction')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('owner_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Post')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('postings', models.IntegerField(default=0)),
                ('subcategories', models.ManyToManyField(to='main.Subcategory')),
            ],
        ),
    ]
