# Generated by Django 3.0.8 on 2020-07-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='main.Subcategory'),
        ),
    ]
