# Generated by Django 3.0.8 on 2020-07-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200730_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
