# Generated by Django 3.0.8 on 2020-07-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_constant'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='other_data',
            field=models.TextField(blank=True),
        ),
    ]
