# Generated by Django 3.0.8 on 2020-08-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200731_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='postings',
        ),
        migrations.AddField(
            model_name='category',
            name='naming',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
